import { Button, Input, Link, Stack, Text } from "@chakra-ui/react"

export const Shortener = () => {
  return (
    <Stack
        position='relative'
        >
        <Stack
            bgImage='url(/images/bg-shorten-desktop.svg)'
            bgRepeat='no-repeat'
            bgSize='cover'
            bgPosition='center'
            bgColor='purple.900'
            pos='absolute'
            top={-16}
            w='100%'
            p={12}
            borderRadius='xl'
            direction='row'
        >
            <Stack
                direction='row'
                w='100%'
                as='form'
            >
                <Input 
                    bgColor='white'
                    placeholder='Shorten a link here...'
                    size='lg'
                />
                <Button
                    colorScheme='teal'
                    size='lg'
                    px={6}
                    type='submit'
                >
                    Shorten It!
                </Button>
            </Stack>
        </Stack>
        <Stack
            pt={20}
        > 
            <Stack
                bg='white'
                borderRadius='md'
                p={4}
                direction='row'
                justify='space-between'
                align='center'
            >
                <Stack>
                    <Link
                        fontWeight={'bold'}
                        href='#'
                    >
                        https://chakra-ui.com/docs/components/container/usage
                    </Link>
                </Stack>
                <Stack
                    direction='row'
                    align='center'
                    gap={3}
                >
                    <Link
                        color='teal.300'
                        align='center'
                        fontWeight='bold'
                        href='#'
                    >
                        https://chakra-ui.com
                    </Link>
                    <Button
                        colorScheme='teal'
                        px={8}
                    >Copy</Button>
                </Stack>
            </Stack>
            <Stack
                bg='white'
                borderRadius='md'
                p={4}
                direction='row'
                justify='space-between'
                align='center'
            >
                <Stack>
                    <Link
                        fontWeight={'bold'}
                        href='#'
                    >
                        https://chakra-ui.com/docs/components/container/usage
                    </Link>
                </Stack>
                <Stack
                    direction='row'
                    align='center'
                    gap={3}
                >
                    <Link
                        color='teal.300'
                        align='center'
                        fontWeight='bold'
                        href='#'
                    >
                        https://chakra-ui.com
                    </Link>
                    <Button
                        colorScheme='teal'
                        px={8}
                    >Copy</Button>
                </Stack>
            </Stack>
        </Stack>
    </Stack>
  )
}
